# Generated by Django 2.2.7 on 2019-12-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20191204_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
