# Generated by Django 2.2.7 on 2019-12-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20191204_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='type',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
