# Generated by Django 2.2.7 on 2019-12-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20191204_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subtype',
        ),
        migrations.DeleteModel(
            name='Subtype',
        ),
    ]
