# Generated by Django 2.2.7 on 2019-12-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20191206_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='color',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
