# Generated by Django 2.2.7 on 2019-12-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_type_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='timestamp',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
