# Generated by Django 2.2.7 on 2019-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20191215_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='size',
            field=models.CharField(default='middle', max_length=6),
        ),
    ]
