# Generated by Django 2.2.7 on 2019-12-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_card_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='size',
        ),
    ]
