# Generated by Django 2.2.7 on 2019-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20191223_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='card_count',
            field=models.IntegerField(default=0),
        ),
    ]
