# Generated by Django 2.2.7 on 2019-12-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0012_type_card_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='card_count',
        ),
    ]
