# Generated by Django 2.2.7 on 2019-12-28 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0013_remove_type_card_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('imgur_url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=9, null=True)),
                ('type', models.CharField(max_length=300, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
