# Generated by Django 2.2.7 on 2019-12-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_postcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcard',
            old_name='tags',
            new_name='tag_list',
        ),
    ]
