# Generated by Django 2.2.7 on 2019-12-06 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191205_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
