# Generated by Django 2.2.7 on 2019-12-12 13:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191206_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_news_check',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 14, 13, 14, 42, 179363, tzinfo=utc)),
        ),
    ]
