# Generated by Django 2.2.7 on 2019-12-14 20:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_last_news_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_news_check',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 16, 20, 36, 19, 534428, tzinfo=utc)),
        ),
    ]
