# Generated by Django 2.2.7 on 2019-12-15 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191215_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_news_check',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 12, 28, 9, 876459, tzinfo=utc)),
        ),
    ]
